FROM openjdk:17.0.1-jdk-oracle

# direktori --> folder aplikasi dalam container, brti nama foldernya /app gitu
WORKDIR /app

# copy jar file --> di folder kita ada file target, hasil dari compile program kita
COPY target/*.jar app.jar

# expose
EXPOSE 8761

# run
CMD ["java", "-jar", "app.jar"]