# 1. Deployment MariaDB
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: wordpress
    tier: mysql
spec:
  replicas: 0
  selector:
    matchLabels:
      app: wordpress
      tier: mysql
  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql
    spec:
      containers:
      - image: mariadb:10.6
        name: mysql-container
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "12345678"
        - name: MYSQL_DATABASE
          value: "wordpress_db_name"
        - name: MYSQL_USER
          value: "wordpress_user"
        - name: MYSQL_PASSWORD
          value: "12345678"
---
# 2. Service MariaDB
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: wordpress
    tier: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: wordpress
    tier: mysql
  type: ClusterIP
---
# --- 3. Deployment WordPress
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: wordpress
    tier: frontend
spec:
  replicas: 0
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: wordpress:latest
        name: wordpress-container
        ports:
        - containerPort: 80
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql-service:3306
        - name: WORDPRESS_DB_USER
          value: wordpress_user
        - name: WORDPRESS_DB_PASSWORD
          value: "12345678"
        - name: WORDPRESS_DB_NAME
          value: wordpress_db_name
---
# 4. Service WordPress
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  labels:
    app: wordpress
    tier: frontend
spec:
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30007
  selector:
    app: wordpress
    tier: frontend
  type: NodePort